Uses dev docker container in the dev branch. No AUTO cherry-pick (#2621)

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -9,13 +9,31 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      DOCKER_ENTERPRISE_DEV_URL: ${{ secrets.DOCKER_ENTERPRISE_DEV_URL }}
+      DOCKER_COMMUNITY_DEV_URL: ${{ secrets.DOCKER_COMMUNITY_DEV_URL }}
+      TEAMCITY_DEV_URL: ${{ secrets.TEAMCITY_DEV_URL }}
+      TEAMCITY_USER: ${{ secrets.TEAMCITY_USER }}
+      TEAMCITY_PASSWORD: ${{ secrets.TEAMCITY_PASSWORD }}
+      ENTERPRISE_TAR: enterprise-docker.tar
+      COMMUNITY_TAR: community-docker.tar
     steps:
       - uses: actions/checkout@v2
+
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'adopt'
+
+      - name: Download neo4j dev docker container
+        run: |
+          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_ENTERPRISE_DEV_URL} -o ${ENTERPRISE_TAR} &
+          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_COMMUNITY_DEV_URL} -o ${COMMUNITY_TAR} &
+          wait
+          docker load --input ${ENTERPRISE_TAR}
+          docker load --input ${COMMUNITY_TAR}
+
       - uses: actions/cache@v2
         with:
           path: |
@@ -24,19 +42,16 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
-      - name: Grant execute permission for gradlew
-        run: chmod +x gradlew
+
       - name: Build with Gradle
-        env:
-          TEAMCITY_DEV_URL: ${{ secrets.TEAMCITY_DEV_URL }}
-          TEAMCITY_USER: ${{ secrets.TEAMCITY_USER }}
-          TEAMCITY_PASSWORD: ${{ secrets.TEAMCITY_PASSWORD }}
-        run: ./gradlew build
-      - name: Clean neo4j from the cache
-        if: success() || failure() # run this step even if previous step failed
-        run: (find ~/.gradle/caches -name "*neo4j*" -exec rm -rf {} \;) || echo "All neo4j files cleaned"
-      - name: Check procedures included in apoc full
-        run: git diff --exit-code full/src/main/resources/extended.txt || (echo "extended.txt file does not contain all changes" && exit -1)
+        run: chmod +x gradlew && ./gradlew build
+
+      - name: Clean neo4j artifacts
+        if: always() # run this step even if previous step failed
+        run: |
+          (find ~/.gradle/caches -name "*neo4j*" -exec rm -rf {} \;) || echo "All neo4j files cleaned"
+          rm -rf ${ENTERPRISE_TAR} ${COMMUNITY_TAR}
+
       - name: Archive test results
         uses: actions/upload-artifact@v2
         if: always()
