debug assemble error

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -16,107 +16,48 @@ env:
   COMMUNITY_TAR: community-docker.tar
   
 jobs:
-  compile:
+  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-#      - uses: actions/checkout@v3
-      - uses: ./.github/actions/setup-jdk
-      - uses: ./.github/actions/setup-gradle-cache #todo - needed?
-      - name: Init submodule
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17.0.8'
+          distribution: 'temurin'
+
+#      - name: Download neo4j dev docker container
+#        run: |
+#          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_ENTERPRISE_URL} -o ${ENTERPRISE_TAR} &
+#          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_COMMUNITY_URL} -o ${COMMUNITY_TAR} &
+#          wait
+#          docker load --input ${ENTERPRISE_TAR}
+#          docker load --input ${COMMUNITY_TAR}
+
+      - uses: actions/cache@v2
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+
+      - name: Build with Gradle
         run: |
           chmod +x gradlew
-          ./gradlew --init-script init.gradle clean
-#        run: ./gradlew --init-script init.gradle clean
-        # run: ./gradlew compileJava compileTestJava #todo - maybe ./gradlew --init-script init.gradle
-        # todo - maybe i can try removing clean and try directly shadowJar --init-script
-#      - name: Compile Java
-#        run: ./gradlew shadowJar
-        
-#        > Task :generateGrammarSource NO-SOURCE
-#        > Task :compileJava NO-SOURCE
-#        > Task :processResources NO-SOURCE
-#        > Task :classes UP-TO-DATE
-#        > Task :jar
-#        > Task :assemble
-#        > Task :generateTestGrammarSource NO-SOURCE
-#        > Task :compileTestJava NO-SOURCE
-#        > Task :processTestResources NO-SOURCE
-#        > Task :testClasses UP-TO-DATE
-#        > Task :test NO-SOURCE
-#        > Task :check UP-TO-DATE - TODO  PROVARE DIRETTAMENTE QUESTO?
-  
-  code-ql:
-    runs-on: ubuntu-latest
-    needs: compile
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [ 'java', 'javascript' ]
-    steps:
-      - uses: actions/checkout@v3
-      - uses: ./.github/actions/setup-jdk
-      - uses: ./.github/actions/setup-gradle-cache #todo - needed?
-        
-       # TODO - provare usando  
-      - name: Compile Java
-        run: ./gradlew --no-daemon --init-script init.gradle clean
-       # TODO - maybe clean remove the gradle-cache?? 
-#        run: ./gradlew --no-daemon --init-script init.gradle clean
-        # run: ./gradlew compileJava compileTestJava #todo - maybe ./gradlew --init-script init.gradle
-      # Initializes the CodeQL tools for scanning.
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v2
-        with:
-          languages: ${{ matrix.language }}
-          
-      # Autobuild attempts to build any compiled languages 
-      - name: Autobuild
-        uses: github/codeql-action/autobuild@v2
-      
-      - name: Perform CodeQL Analysis
-        uses: github/codeql-action/analyze@v2
-        with:
-          category: "/language:${{matrix.language}}"
-       
-  assemble:
-    runs-on: ubuntu-latest
-    needs: compile
-    steps:
-      - uses: actions/checkout@v2
-      - uses: ./.github/actions/setup-jdk
-      - name: Assemble
-        run: ./gradlew build --parallel
-#        run: ./gradlew assemble --parallel
-        
-  tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        project: [ 'extended', 'extended-it' ]
-    env:
-      DOCKER_ENTERPRISE_DEV_URL: ${{ secrets.DOCKER_ENTERPRISE_DEV_URL }}
-      DOCKER_COMMUNITY_DEV_URL: ${{ secrets.DOCKER_COMMUNITY_DEV_URL }}
-      ENTERPRISE_TAR: enterprise-docker.tar
-      COMMUNITY_TAR: community-docker.tar
-    runs-on: ubuntu-latest
-    needs: assemble
-    steps:
-#      - uses: actions/checkout@v2
-      - name: Download neo4j dev docker container
-        if: matrix.project == 'enterprise-it'
-        run: |
-          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_ENTERPRISE_URL} -o ${ENTERPRISE_TAR} &
-          curl -s -L0 -u "${TEAMCITY_USER}:${TEAMCITY_PASSWORD}" -X GET ${DOCKER_COMMUNITY_URL} -o ${COMMUNITY_TAR} &
-          wait
-          docker load --input ${ENTERPRISE_TAR}
-          docker load --input ${COMMUNITY_TAR}
-        
-      - name: Run ${{ matrix.project }} tests
-        uses: ./.github/actions/test-gradle-project
-        with:
-          project-name: ${{ matrix.project }}
+          ./gradlew --init-script init.gradle
+          ./gradlew assemble --parallel
+
+#      - name: Clean neo4j artifacts
+#        if: always() # run this step even if previous step failed
+#        run: |
+#          (find ~/.gradle/caches -name "*neo4j*" -exec rm -rf {} \;) || echo "All neo4j files cleaned"
+#          rm -rf ${ENTERPRISE_TAR} ${COMMUNITY_TAR}
+#
+#      - name: Archive test results
+#        uses: actions/upload-artifact@v2
+#        if: always()
+#        with:
+#          name: test-results
+#          path: |
+#            extended/build/reports/tests/test/
